feat(helm): added chart for k8s deployment
MapColonies/dump-server pull request #13
Opened 2021-03-16 13:15 UTC by melancholiai

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

Closes #11 

- Breaking changes are due to the addition of object-storage port in the configuration and it's need in business logic

2021-03-18 11:39 UTC, CptSchnitz requested changes

2021-03-18 11:39 UTC, CptSchnitz commented on .gitignore
> +helm/myvalues.yaml
```suggestion
**/myvalues.yaml
```

2021-03-18 12:23 UTC, syncush approved these changes

2021-03-21 07:18 UTC, CptSchnitz approved these changes

2021-03-21 08:02 UTC, merged